// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// DepositRequest is the predicate function for depositrequest builders.
type DepositRequest func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// TransactionDetails is the predicate function for transactiondetails builders.
type TransactionDetails func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
