version : '3'

services:
  db:
    image: mysql:8.0
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
