GET http://localhost:5432/api/accounts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwaXJlcyI6MTcwMzYwNjA0OSwibnVtYmVyIjoiMDI5NTQ5MjAifQ.5Odh5Dep_aQwH7a4UWb0V_2fqMVNpZ94y_dHoUcnItI

GET http://localhost:5432/api/accounts/05898155
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cGlyZXMiOjE3MDM0MjI1MDcsIm51bWJlciI6IjA1ODk4MTU1In0.3ZC95xJg2VJ0Ds2Hl3ErX1yHglXuwBble_5m3KCWc-U

DELETE http://localhost:5432/api/accounts/03483281
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cGlyZXMiOjE3MDMzNjg4MjMsIm51bWJlciI6IjAzNDgzMjgxIn0.-HujP6FnEq2Nt2i69LQjlp8lot5q-i4LBx5vkXhho6s

POST http://localhost:5432/auth
Content-Type: application/json

{
    "number": "02954920",
    "password": "eusouoadmin"
}

POST http://localhost:5432/auth/new
Content-Type: application/json

{
    "firstName": "Benjamin",
    "lastName": "Raposo",
    "password": "eusouumcachorro",
    "email": "benji@rick.com"
}

POST http://localhost:5432/api/deposit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwaXJlcyI6MTcwMzUyNzIyNywibnVtYmVyIjoiMDI5NTQ5MjAifQ.EPzNCbnyTyeeFotpxyy6FtrsVXvpugoOpQoHUPKlfKE
Content-Type: application/json

{
    "toAccountNumber": "02954920",
    "amount": 1000
}

POST http://localhost:5432/api/withdraw
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwaXJlcyI6MTcwMzUyNzIyNywibnVtYmVyIjoiMDI5NTQ5MjAifQ.EPzNCbnyTyeeFotpxyy6FtrsVXvpugoOpQoHUPKlfKE
Content-Type: application/json

{
    "fromAccountNumber": "02954920",
    "amount": 10
}

POST http://localhost:5432/api/transfer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwaXJlcyI6MTcwMzUyNzIyNywibnVtYmVyIjoiMDI5NTQ5MjAifQ.EPzNCbnyTyeeFotpxyy6FtrsVXvpugoOpQoHUPKlfKE
Content-Type: application/json

{
    "fromAccountNumber": "02954920",
    "toAccountNumber": "02918553",
    "amount": 10
}

POST http://localhost:5432/api/favorite
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwaXJlcyI6MTcwMzUxNDE4NCwibnVtYmVyIjoiMDExNjQ4NTYifQ.C6zwUGk64vp-rj_MJh_U-aOMmrBtyvOPwxVLFL77Ldo
Content-Type: application/json

{
    "accountID": "01164856",
    "favoritedID": "01479248"
}

GET http://localhost:5432/api/transaction
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwaXJlcyI6MTcwMzYwNjA0OSwibnVtYmVyIjoiMDI5NTQ5MjAifQ.5Odh5Dep_aQwH7a4UWb0V_2fqMVNpZ94y_dHoUcnItI

GET http://localhost:5432/api/transaction/02954920
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwaXJlcyI6MTcwMzYwNjA0OSwibnVtYmVyIjoiMDI5NTQ5MjAifQ.5Odh5Dep_aQwH7a4UWb0V_2fqMVNpZ94y_dHoUcnItI
