// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ricardoraposo/gopherbank/ent/depositrequest"
	"github.com/ricardoraposo/gopherbank/ent/predicate"
)

// DepositRequestDelete is the builder for deleting a DepositRequest entity.
type DepositRequestDelete struct {
	config
	hooks    []Hook
	mutation *DepositRequestMutation
}

// Where appends a list predicates to the DepositRequestDelete builder.
func (drd *DepositRequestDelete) Where(ps ...predicate.DepositRequest) *DepositRequestDelete {
	drd.mutation.Where(ps...)
	return drd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (drd *DepositRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, drd.sqlExec, drd.mutation, drd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (drd *DepositRequestDelete) ExecX(ctx context.Context) int {
	n, err := drd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (drd *DepositRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(depositrequest.Table, sqlgraph.NewFieldSpec(depositrequest.FieldID, field.TypeInt))
	if ps := drd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, drd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	drd.mutation.done = true
	return affected, err
}

// DepositRequestDeleteOne is the builder for deleting a single DepositRequest entity.
type DepositRequestDeleteOne struct {
	drd *DepositRequestDelete
}

// Where appends a list predicates to the DepositRequestDelete builder.
func (drdo *DepositRequestDeleteOne) Where(ps ...predicate.DepositRequest) *DepositRequestDeleteOne {
	drdo.drd.mutation.Where(ps...)
	return drdo
}

// Exec executes the deletion query.
func (drdo *DepositRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := drdo.drd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{depositrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (drdo *DepositRequestDeleteOne) ExecX(ctx context.Context) {
	if err := drdo.Exec(ctx); err != nil {
		panic(err)
	}
}
