// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ricardoraposo/gopherbank/ent/account"
	"github.com/ricardoraposo/gopherbank/ent/schema"
	"github.com/ricardoraposo/gopherbank/ent/transactiondetail"
	"github.com/ricardoraposo/gopherbank/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescBalance is the schema descriptor for balance field.
	accountDescBalance := accountFields[2].Descriptor()
	// account.DefaultBalance holds the default value on creation for the balance field.
	account.DefaultBalance = accountDescBalance.Default.(float64)
	// accountDescCreatedAt is the schema descriptor for createdAt field.
	accountDescCreatedAt := accountFields[3].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the createdAt field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescAdmin is the schema descriptor for admin field.
	accountDescAdmin := accountFields[4].Descriptor()
	// account.DefaultAdmin holds the default value on creation for the admin field.
	account.DefaultAdmin = accountDescAdmin.Default.(bool)
	transactiondetailFields := schema.TransactionDetail{}.Fields()
	_ = transactiondetailFields
	// transactiondetailDescType is the schema descriptor for type field.
	transactiondetailDescType := transactiondetailFields[2].Descriptor()
	// transactiondetail.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	transactiondetail.TypeValidator = transactiondetailDescType.Validators[0].(func(string) error)
	// transactiondetailDescTransactedAt is the schema descriptor for transacted_at field.
	transactiondetailDescTransactedAt := transactiondetailFields[3].Descriptor()
	// transactiondetail.DefaultTransactedAt holds the default value on creation for the transacted_at field.
	transactiondetail.DefaultTransactedAt = transactiondetailDescTransactedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[1].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[2].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
}
