// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ricardoraposo/gopherbank/ent/predicate"
	"github.com/ricardoraposo/gopherbank/ent/transaction"
	"github.com/ricardoraposo/gopherbank/ent/transactiondetail"
)

// TransactionDetailUpdate is the builder for updating TransactionDetail entities.
type TransactionDetailUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionDetailMutation
}

// Where appends a list predicates to the TransactionDetailUpdate builder.
func (tdu *TransactionDetailUpdate) Where(ps ...predicate.TransactionDetail) *TransactionDetailUpdate {
	tdu.mutation.Where(ps...)
	return tdu
}

// SetAmount sets the "amount" field.
func (tdu *TransactionDetailUpdate) SetAmount(f float64) *TransactionDetailUpdate {
	tdu.mutation.ResetAmount()
	tdu.mutation.SetAmount(f)
	return tdu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tdu *TransactionDetailUpdate) SetNillableAmount(f *float64) *TransactionDetailUpdate {
	if f != nil {
		tdu.SetAmount(*f)
	}
	return tdu
}

// AddAmount adds f to the "amount" field.
func (tdu *TransactionDetailUpdate) AddAmount(f float64) *TransactionDetailUpdate {
	tdu.mutation.AddAmount(f)
	return tdu
}

// SetType sets the "type" field.
func (tdu *TransactionDetailUpdate) SetType(s string) *TransactionDetailUpdate {
	tdu.mutation.SetType(s)
	return tdu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tdu *TransactionDetailUpdate) SetNillableType(s *string) *TransactionDetailUpdate {
	if s != nil {
		tdu.SetType(*s)
	}
	return tdu
}

// SetTransactionID sets the "transaction" edge to the Transaction entity by ID.
func (tdu *TransactionDetailUpdate) SetTransactionID(id int) *TransactionDetailUpdate {
	tdu.mutation.SetTransactionID(id)
	return tdu
}

// SetNillableTransactionID sets the "transaction" edge to the Transaction entity by ID if the given value is not nil.
func (tdu *TransactionDetailUpdate) SetNillableTransactionID(id *int) *TransactionDetailUpdate {
	if id != nil {
		tdu = tdu.SetTransactionID(*id)
	}
	return tdu
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (tdu *TransactionDetailUpdate) SetTransaction(t *Transaction) *TransactionDetailUpdate {
	return tdu.SetTransactionID(t.ID)
}

// Mutation returns the TransactionDetailMutation object of the builder.
func (tdu *TransactionDetailUpdate) Mutation() *TransactionDetailMutation {
	return tdu.mutation
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (tdu *TransactionDetailUpdate) ClearTransaction() *TransactionDetailUpdate {
	tdu.mutation.ClearTransaction()
	return tdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tdu *TransactionDetailUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tdu.sqlSave, tdu.mutation, tdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tdu *TransactionDetailUpdate) SaveX(ctx context.Context) int {
	affected, err := tdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tdu *TransactionDetailUpdate) Exec(ctx context.Context) error {
	_, err := tdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdu *TransactionDetailUpdate) ExecX(ctx context.Context) {
	if err := tdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tdu *TransactionDetailUpdate) check() error {
	if v, ok := tdu.mutation.GetType(); ok {
		if err := transactiondetail.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TransactionDetail.type": %w`, err)}
		}
	}
	return nil
}

func (tdu *TransactionDetailUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(transactiondetail.Table, transactiondetail.Columns, sqlgraph.NewFieldSpec(transactiondetail.FieldID, field.TypeInt))
	if ps := tdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tdu.mutation.Amount(); ok {
		_spec.SetField(transactiondetail.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tdu.mutation.AddedAmount(); ok {
		_spec.AddField(transactiondetail.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tdu.mutation.GetType(); ok {
		_spec.SetField(transactiondetail.FieldType, field.TypeString, value)
	}
	if tdu.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transactiondetail.TransactionTable,
			Columns: []string{transactiondetail.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tdu.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transactiondetail.TransactionTable,
			Columns: []string{transactiondetail.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactiondetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tdu.mutation.done = true
	return n, nil
}

// TransactionDetailUpdateOne is the builder for updating a single TransactionDetail entity.
type TransactionDetailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionDetailMutation
}

// SetAmount sets the "amount" field.
func (tduo *TransactionDetailUpdateOne) SetAmount(f float64) *TransactionDetailUpdateOne {
	tduo.mutation.ResetAmount()
	tduo.mutation.SetAmount(f)
	return tduo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tduo *TransactionDetailUpdateOne) SetNillableAmount(f *float64) *TransactionDetailUpdateOne {
	if f != nil {
		tduo.SetAmount(*f)
	}
	return tduo
}

// AddAmount adds f to the "amount" field.
func (tduo *TransactionDetailUpdateOne) AddAmount(f float64) *TransactionDetailUpdateOne {
	tduo.mutation.AddAmount(f)
	return tduo
}

// SetType sets the "type" field.
func (tduo *TransactionDetailUpdateOne) SetType(s string) *TransactionDetailUpdateOne {
	tduo.mutation.SetType(s)
	return tduo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tduo *TransactionDetailUpdateOne) SetNillableType(s *string) *TransactionDetailUpdateOne {
	if s != nil {
		tduo.SetType(*s)
	}
	return tduo
}

// SetTransactionID sets the "transaction" edge to the Transaction entity by ID.
func (tduo *TransactionDetailUpdateOne) SetTransactionID(id int) *TransactionDetailUpdateOne {
	tduo.mutation.SetTransactionID(id)
	return tduo
}

// SetNillableTransactionID sets the "transaction" edge to the Transaction entity by ID if the given value is not nil.
func (tduo *TransactionDetailUpdateOne) SetNillableTransactionID(id *int) *TransactionDetailUpdateOne {
	if id != nil {
		tduo = tduo.SetTransactionID(*id)
	}
	return tduo
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (tduo *TransactionDetailUpdateOne) SetTransaction(t *Transaction) *TransactionDetailUpdateOne {
	return tduo.SetTransactionID(t.ID)
}

// Mutation returns the TransactionDetailMutation object of the builder.
func (tduo *TransactionDetailUpdateOne) Mutation() *TransactionDetailMutation {
	return tduo.mutation
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (tduo *TransactionDetailUpdateOne) ClearTransaction() *TransactionDetailUpdateOne {
	tduo.mutation.ClearTransaction()
	return tduo
}

// Where appends a list predicates to the TransactionDetailUpdate builder.
func (tduo *TransactionDetailUpdateOne) Where(ps ...predicate.TransactionDetail) *TransactionDetailUpdateOne {
	tduo.mutation.Where(ps...)
	return tduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tduo *TransactionDetailUpdateOne) Select(field string, fields ...string) *TransactionDetailUpdateOne {
	tduo.fields = append([]string{field}, fields...)
	return tduo
}

// Save executes the query and returns the updated TransactionDetail entity.
func (tduo *TransactionDetailUpdateOne) Save(ctx context.Context) (*TransactionDetail, error) {
	return withHooks(ctx, tduo.sqlSave, tduo.mutation, tduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tduo *TransactionDetailUpdateOne) SaveX(ctx context.Context) *TransactionDetail {
	node, err := tduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tduo *TransactionDetailUpdateOne) Exec(ctx context.Context) error {
	_, err := tduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tduo *TransactionDetailUpdateOne) ExecX(ctx context.Context) {
	if err := tduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tduo *TransactionDetailUpdateOne) check() error {
	if v, ok := tduo.mutation.GetType(); ok {
		if err := transactiondetail.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TransactionDetail.type": %w`, err)}
		}
	}
	return nil
}

func (tduo *TransactionDetailUpdateOne) sqlSave(ctx context.Context) (_node *TransactionDetail, err error) {
	if err := tduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transactiondetail.Table, transactiondetail.Columns, sqlgraph.NewFieldSpec(transactiondetail.FieldID, field.TypeInt))
	id, ok := tduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransactionDetail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transactiondetail.FieldID)
		for _, f := range fields {
			if !transactiondetail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transactiondetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tduo.mutation.Amount(); ok {
		_spec.SetField(transactiondetail.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tduo.mutation.AddedAmount(); ok {
		_spec.AddField(transactiondetail.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tduo.mutation.GetType(); ok {
		_spec.SetField(transactiondetail.FieldType, field.TypeString, value)
	}
	if tduo.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transactiondetail.TransactionTable,
			Columns: []string{transactiondetail.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tduo.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transactiondetail.TransactionTable,
			Columns: []string{transactiondetail.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TransactionDetail{config: tduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactiondetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tduo.mutation.done = true
	return _node, nil
}
