// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ricardoraposo/gopherbank/ent/predicate"
	"github.com/ricardoraposo/gopherbank/ent/transaction"
	"github.com/ricardoraposo/gopherbank/ent/transactiondetails"
)

// TransactionDetailsQuery is the builder for querying TransactionDetails entities.
type TransactionDetailsQuery struct {
	config
	ctx             *QueryContext
	order           []transactiondetails.OrderOption
	inters          []Interceptor
	predicates      []predicate.TransactionDetails
	withTransaction *TransactionQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TransactionDetailsQuery builder.
func (tdq *TransactionDetailsQuery) Where(ps ...predicate.TransactionDetails) *TransactionDetailsQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit the number of records to be returned by this query.
func (tdq *TransactionDetailsQuery) Limit(limit int) *TransactionDetailsQuery {
	tdq.ctx.Limit = &limit
	return tdq
}

// Offset to start from.
func (tdq *TransactionDetailsQuery) Offset(offset int) *TransactionDetailsQuery {
	tdq.ctx.Offset = &offset
	return tdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tdq *TransactionDetailsQuery) Unique(unique bool) *TransactionDetailsQuery {
	tdq.ctx.Unique = &unique
	return tdq
}

// Order specifies how the records should be ordered.
func (tdq *TransactionDetailsQuery) Order(o ...transactiondetails.OrderOption) *TransactionDetailsQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// QueryTransaction chains the current query on the "transaction" edge.
func (tdq *TransactionDetailsQuery) QueryTransaction() *TransactionQuery {
	query := (&TransactionClient{config: tdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transactiondetails.Table, transactiondetails.FieldID, selector),
			sqlgraph.To(transaction.Table, transaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, transactiondetails.TransactionTable, transactiondetails.TransactionColumn),
		)
		fromU = sqlgraph.SetNeighbors(tdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TransactionDetails entity from the query.
// Returns a *NotFoundError when no TransactionDetails was found.
func (tdq *TransactionDetailsQuery) First(ctx context.Context) (*TransactionDetails, error) {
	nodes, err := tdq.Limit(1).All(setContextOp(ctx, tdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{transactiondetails.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *TransactionDetailsQuery) FirstX(ctx context.Context) *TransactionDetails {
	node, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TransactionDetails ID from the query.
// Returns a *NotFoundError when no TransactionDetails ID was found.
func (tdq *TransactionDetailsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(1).IDs(setContextOp(ctx, tdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{transactiondetails.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tdq *TransactionDetailsQuery) FirstIDX(ctx context.Context) int {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TransactionDetails entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TransactionDetails entity is found.
// Returns a *NotFoundError when no TransactionDetails entities are found.
func (tdq *TransactionDetailsQuery) Only(ctx context.Context) (*TransactionDetails, error) {
	nodes, err := tdq.Limit(2).All(setContextOp(ctx, tdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{transactiondetails.Label}
	default:
		return nil, &NotSingularError{transactiondetails.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *TransactionDetailsQuery) OnlyX(ctx context.Context) *TransactionDetails {
	node, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TransactionDetails ID in the query.
// Returns a *NotSingularError when more than one TransactionDetails ID is found.
// Returns a *NotFoundError when no entities are found.
func (tdq *TransactionDetailsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(2).IDs(setContextOp(ctx, tdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{transactiondetails.Label}
	default:
		err = &NotSingularError{transactiondetails.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *TransactionDetailsQuery) OnlyIDX(ctx context.Context) int {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TransactionDetailsSlice.
func (tdq *TransactionDetailsQuery) All(ctx context.Context) ([]*TransactionDetails, error) {
	ctx = setContextOp(ctx, tdq.ctx, "All")
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TransactionDetails, *TransactionDetailsQuery]()
	return withInterceptors[[]*TransactionDetails](ctx, tdq, qr, tdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tdq *TransactionDetailsQuery) AllX(ctx context.Context) []*TransactionDetails {
	nodes, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TransactionDetails IDs.
func (tdq *TransactionDetailsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tdq.ctx.Unique == nil && tdq.path != nil {
		tdq.Unique(true)
	}
	ctx = setContextOp(ctx, tdq.ctx, "IDs")
	if err = tdq.Select(transactiondetails.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *TransactionDetailsQuery) IDsX(ctx context.Context) []int {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *TransactionDetailsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tdq.ctx, "Count")
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tdq, querierCount[*TransactionDetailsQuery](), tdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *TransactionDetailsQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *TransactionDetailsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tdq.ctx, "Exist")
	switch _, err := tdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *TransactionDetailsQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TransactionDetailsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *TransactionDetailsQuery) Clone() *TransactionDetailsQuery {
	if tdq == nil {
		return nil
	}
	return &TransactionDetailsQuery{
		config:          tdq.config,
		ctx:             tdq.ctx.Clone(),
		order:           append([]transactiondetails.OrderOption{}, tdq.order...),
		inters:          append([]Interceptor{}, tdq.inters...),
		predicates:      append([]predicate.TransactionDetails{}, tdq.predicates...),
		withTransaction: tdq.withTransaction.Clone(),
		// clone intermediate query.
		sql:  tdq.sql.Clone(),
		path: tdq.path,
	}
}

// WithTransaction tells the query-builder to eager-load the nodes that are connected to
// the "transaction" edge. The optional arguments are used to configure the query builder of the edge.
func (tdq *TransactionDetailsQuery) WithTransaction(opts ...func(*TransactionQuery)) *TransactionDetailsQuery {
	query := (&TransactionClient{config: tdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tdq.withTransaction = query
	return tdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Amount float64 `json:"amount"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TransactionDetails.Query().
//		GroupBy(transactiondetails.FieldAmount).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tdq *TransactionDetailsQuery) GroupBy(field string, fields ...string) *TransactionDetailsGroupBy {
	tdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TransactionDetailsGroupBy{build: tdq}
	grbuild.flds = &tdq.ctx.Fields
	grbuild.label = transactiondetails.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Amount float64 `json:"amount"`
//	}
//
//	client.TransactionDetails.Query().
//		Select(transactiondetails.FieldAmount).
//		Scan(ctx, &v)
func (tdq *TransactionDetailsQuery) Select(fields ...string) *TransactionDetailsSelect {
	tdq.ctx.Fields = append(tdq.ctx.Fields, fields...)
	sbuild := &TransactionDetailsSelect{TransactionDetailsQuery: tdq}
	sbuild.label = transactiondetails.Label
	sbuild.flds, sbuild.scan = &tdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TransactionDetailsSelect configured with the given aggregations.
func (tdq *TransactionDetailsQuery) Aggregate(fns ...AggregateFunc) *TransactionDetailsSelect {
	return tdq.Select().Aggregate(fns...)
}

func (tdq *TransactionDetailsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tdq); err != nil {
				return err
			}
		}
	}
	for _, f := range tdq.ctx.Fields {
		if !transactiondetails.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *TransactionDetailsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TransactionDetails, error) {
	var (
		nodes       = []*TransactionDetails{}
		withFKs     = tdq.withFKs
		_spec       = tdq.querySpec()
		loadedTypes = [1]bool{
			tdq.withTransaction != nil,
		}
	)
	if tdq.withTransaction != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, transactiondetails.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TransactionDetails).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TransactionDetails{config: tdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tdq.withTransaction; query != nil {
		if err := tdq.loadTransaction(ctx, query, nodes, nil,
			func(n *TransactionDetails, e *Transaction) { n.Edges.Transaction = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tdq *TransactionDetailsQuery) loadTransaction(ctx context.Context, query *TransactionQuery, nodes []*TransactionDetails, init func(*TransactionDetails), assign func(*TransactionDetails, *Transaction)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TransactionDetails)
	for i := range nodes {
		if nodes[i].transaction_id == nil {
			continue
		}
		fk := *nodes[i].transaction_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(transaction.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "transaction_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tdq *TransactionDetailsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	_spec.Node.Columns = tdq.ctx.Fields
	if len(tdq.ctx.Fields) > 0 {
		_spec.Unique = tdq.ctx.Unique != nil && *tdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *TransactionDetailsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(transactiondetails.Table, transactiondetails.Columns, sqlgraph.NewFieldSpec(transactiondetails.FieldID, field.TypeInt))
	_spec.From = tdq.sql
	if unique := tdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tdq.path != nil {
		_spec.Unique = true
	}
	if fields := tdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transactiondetails.FieldID)
		for i := range fields {
			if fields[i] != transactiondetails.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *TransactionDetailsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(transactiondetails.Table)
	columns := tdq.ctx.Fields
	if len(columns) == 0 {
		columns = transactiondetails.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tdq.ctx.Unique != nil && *tdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TransactionDetailsGroupBy is the group-by builder for TransactionDetails entities.
type TransactionDetailsGroupBy struct {
	selector
	build *TransactionDetailsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *TransactionDetailsGroupBy) Aggregate(fns ...AggregateFunc) *TransactionDetailsGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the selector query and scans the result into the given value.
func (tdgb *TransactionDetailsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tdgb.build.ctx, "GroupBy")
	if err := tdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransactionDetailsQuery, *TransactionDetailsGroupBy](ctx, tdgb.build, tdgb, tdgb.build.inters, v)
}

func (tdgb *TransactionDetailsGroupBy) sqlScan(ctx context.Context, root *TransactionDetailsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tdgb.fns))
	for _, fn := range tdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tdgb.flds)+len(tdgb.fns))
		for _, f := range *tdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TransactionDetailsSelect is the builder for selecting fields of TransactionDetails entities.
type TransactionDetailsSelect struct {
	*TransactionDetailsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tds *TransactionDetailsSelect) Aggregate(fns ...AggregateFunc) *TransactionDetailsSelect {
	tds.fns = append(tds.fns, fns...)
	return tds
}

// Scan applies the selector query and scans the result into the given value.
func (tds *TransactionDetailsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tds.ctx, "Select")
	if err := tds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransactionDetailsQuery, *TransactionDetailsSelect](ctx, tds.TransactionDetailsQuery, tds, tds.inters, v)
}

func (tds *TransactionDetailsSelect) sqlScan(ctx context.Context, root *TransactionDetailsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tds.fns))
	for _, fn := range tds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
