// Code generated by ent, DO NOT EDIT.

package transactiondetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ricardoraposo/gopherbank/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldLTE(FieldID, id))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEQ(FieldAmount, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEQ(FieldType, v))
}

// TransactedAt applies equality check predicate on the "transacted_at" field. It's identical to TransactedAtEQ.
func TransactedAt(v time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEQ(FieldTransactedAt, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldLTE(FieldAmount, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldContainsFold(FieldType, v))
}

// TransactedAtEQ applies the EQ predicate on the "transacted_at" field.
func TransactedAtEQ(v time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldEQ(FieldTransactedAt, v))
}

// TransactedAtNEQ applies the NEQ predicate on the "transacted_at" field.
func TransactedAtNEQ(v time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldNEQ(FieldTransactedAt, v))
}

// TransactedAtIn applies the In predicate on the "transacted_at" field.
func TransactedAtIn(vs ...time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldIn(FieldTransactedAt, vs...))
}

// TransactedAtNotIn applies the NotIn predicate on the "transacted_at" field.
func TransactedAtNotIn(vs ...time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldNotIn(FieldTransactedAt, vs...))
}

// TransactedAtGT applies the GT predicate on the "transacted_at" field.
func TransactedAtGT(v time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldGT(FieldTransactedAt, v))
}

// TransactedAtGTE applies the GTE predicate on the "transacted_at" field.
func TransactedAtGTE(v time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldGTE(FieldTransactedAt, v))
}

// TransactedAtLT applies the LT predicate on the "transacted_at" field.
func TransactedAtLT(v time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldLT(FieldTransactedAt, v))
}

// TransactedAtLTE applies the LTE predicate on the "transacted_at" field.
func TransactedAtLTE(v time.Time) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.FieldLTE(FieldTransactedAt, v))
}

// HasTransaction applies the HasEdge predicate on the "transaction" edge.
func HasTransaction() predicate.TransactionDetail {
	return predicate.TransactionDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TransactionTable, TransactionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionWith applies the HasEdge predicate on the "transaction" edge with a given conditions (other predicates).
func HasTransactionWith(preds ...predicate.Transaction) predicate.TransactionDetail {
	return predicate.TransactionDetail(func(s *sql.Selector) {
		step := newTransactionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TransactionDetail) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TransactionDetail) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TransactionDetail) predicate.TransactionDetail {
	return predicate.TransactionDetail(sql.NotPredicates(p))
}
