apiVersion: v1
kind: Pod
metadata:
  name: "mysql-db"
  namespace: default
  labels:
    app: "mysql-db"
spec:
  containers:
  - name: mysql-db
    image: "mysql:8.0"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: supersecret
    - name: MYSQL_DATABASE
      value: gopherbank
    ports:
    - containerPort: 3306
